services:
  - name: server
    plan: free
    type: web
    env: node
    repo: https://github.com/jsnorek/GAMESHELF
    buildCommand: cd client && npm install && npm run build && cd ../server && npm install
    startCommand: cd server && npm run migrate && node server.js && cd client && npm run build
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: db
          property: connectionString

databases:
  - name: db
    plan: free
    ipAllowList: []
