services:
  - name: server
    plan: free
    type: web
    env: node
    repo: https://github.com/jsnorek/techtonica-projects.git
    buildCommand: cd client && npm install && npm run build && cd ../server && npm install
    startCommand: cd server && npm run migrate && node server.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: db
          property: connectionString
 - name: frontend
    plan: free
    type: web
    env: static 
    repo: https://github.com/jsnorek/techtonica-projects.git
    staticPublishPath: client/build
    buildCommand: cd client && npm install && npm run build
    envVars: []

databases:
  - name: db
    plan: free
    ipAllowList: []
